variable "rg-location" {}
variable "rg-name" {}
variable "location-prefix" {}
variable "customer-name" {}
variable "env" {}
variable "createdby" {} 
variable "creationdate" {}
variable "aks-default-np-vm-size" {}
variable "subnet-id" {}
variable "la-workspace-resource-id" {}
variable "aks-user-np-vm-size" {}
